### ISSUE TITLE
HP02 & HP09 Do Not Connect

### ISSUE THREAD

**Issue by TonyMontuna** [libdyson-wg/ha-dyson#101]
I have tried several different fixes: 

1. Restart/Reboot all fans 
2. Disable and Re-enable Integration 
3. HP02 is not found 
4. HP09 is found but gets the following error "Failed to connect. The IP Address may be required if your Home Assistant installation is running in a Container or a VM."
5. I am inputting the IP address for the HP09 and it still gets the same error

I am running the following on a dedicated Dell Optiplex mini PC
Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231030.2

**Comment by dotvezz** [comment]
Hi @TonyMontuna! Were you able to perform the debugging steps I described [here](https://github.com/libdyson-wg/ha-dyson/issues/23#issuecomment-1660271507) and also linked [here](https://github.com/libdyson-wg/ha-dyson/issues/67#issuecomment-1712773706) on your previously opened issues?
