### ISSUE TITLE
Particulants

### ISSUE THREAD

**Issue by rywalters** [libdyson-wg/ha-dyson#103]
The older Dyson integration gave me an entity for particulates (PM2.5 I believe) for my Pure Hot + Cool Link fan. This integration doesn't seem to have that entity. Could that be added?

**Comment by dotvezz** [comment]
Hi there! Can you confirm your product code? The product code is a three-digit number possibly followed by a letter like E or K, and can be found in the "Device info" section of your device config page in Home Assistant For the Dyson Pure Hot+Cool, the expected value is 527.

I happen to have a 527, and I can confirm the PM 2.5 and PM 10 sensors are both supported. I know this screenshot doesn't help solve your problem, but it should be similar to what you see. 

![image](https://github.com/libdyson-wg/ha-dyson/assets/4571263/52cf3b6c-55cc-4af0-bca0-2ac51c8b3423)

**Comment by rywalters** [comment]
Hi! My product code is 455. I don't have those particular sensors, nor that nitrogen dioxide sensor. I confirmed the product name (Dyson Pure Hot + Cool Link) in the Dyson app.

**Comment by dotvezz** [comment]
Ahh sorry for the confusion, it's my fault for being dumb; I didn't see the word "Link" in your original message.

This is actually a case of the old integration being incorrect. An earlier contributor took readings from that sensor and assumed it was particulates, but it was actually AQI data coming from the device.

So in this case, the new integration no longer provides "Particulate" and instead provides  a new sensor called "Air Quality Index". Are you able to confirm whether you see this AQI sensor for your device?

**Comment by rywalters** [comment]
Ah, good to know. I do see the AQI sensor (as well as one for VOCs). I wish I had a machine capable of reporting particulate levels! I've been fooled by the old integration all this time...

**Comment by dotvezz** [comment]
Sorry to disappoint! If you want, a little bit more information is available in the release notes for v0.19.1 https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.19.1
