### ISSUE TITLE
Round error on temperature 

### ISSUE THREAD

**Issue by ineedhungry** [libdyson-wg/ha-dyson#105]
Temperature decimal place is extremely long.  Currently displaying 74.930000000000040 °F
<img width="300" alt="image" src="https://github.com/libdyson-wg/ha-dyson/assets/10365569/1edd7e6c-0964-4e5e-957f-3d98b9437ac2">

**Comment by tbulding** [comment]
If you go the temperature entity, you can set the precision from no decimals to 6.

**Comment by ineedhungry** [comment]
Duh! Thanks!
