### ISSUE TITLE
PH01 Humidifier unavailable

### ISSUE THREAD

**Issue by WendelFelius** [libdyson-wg/ha-dyson#108]
Dyson: PH01 (Pure Humidify+Cool)
HA: 2024.1
ha-dyson: 1.3.6

I was using shenxn/ha-dyson before, but completely deleted it and started using libdyson-wg/ha-dyson yesterday (thanks for the continues support!). The fan now works brilliant, but I can't get the humidifier to work. Says it's unavailable. Anything I can do in order to fix this?

![Screenshot 2024-01-04 om 08 44 48@2x](https://github.com/libdyson-wg/ha-dyson/assets/8288091/c5f62c5d-42f9-42db-8ea4-6b4b61ea2a0d)
![Screenshot 2024-01-04 om 08 45 19@2x](https://github.com/libdyson-wg/ha-dyson/assets/8288091/054b2a81-61bd-4304-9358-2325350ca18c)

**Comment by gerdschadler** [comment]
Same issue after upgrading to ha 2024.1

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/107026
https://github.com/home-assistant/core/milestone/640?closed=1

**Comment by bdraco** [comment]
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation/

**Comment by dotvezz** [comment]
Ahh, I've been working on a more complete update since (until now) the deprecated features were non-breaking for this integration. But I'll get out a mini-release tonight to get humidifiers working again.

**Comment by mundschenk-at** [comment]
This is mitigated by HA 2024.1.1 which was just released.

**Comment by dotvezz** [comment]
Nice. That gives me some time to finish the comprehensive cleanup. Thanks for the info @mundschenk-at

**Comment by bmarinov** [comment]
I am not sure that this is related, but I just updated to HA 2024.1.1 and im unable to add the integration at all.
Device: TP07
Error:
>  This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

**Comment by LeeHarvey94** [comment]
This issue is also impacting my Purifier Hot+Cool Formaldehyde (climate and fan entities) since 2024.1 it's been showing as no longer being provided by the dyson_local integration.

**Comment by codyc1515** [comment]
This should be resolved now on the latest version.

**Comment by dotvezz** [comment]
@codyc1515 you're beating me everywhere these days! Everyone having issues, please feel free to follow up if 1.3.7 doesn't resolve your problems.
