### ISSUE TITLE
CN server seem doesn't work properly.

### ISSUE THREAD

**Issue by msdurex** [libdyson-wg/ha-dyson#121]
I have a 360 Heurist vacuum robot in CN server. After I bound this account. Can't discover any device.

**Comment by dotvezz** [comment]
Interesting! Are you able to confirm whether the `get_devices.py` script on the [libdyson-neon](https://github.com/libdyson-wg/libdyson-neon) repository works for you?

**Comment by dotvezz** [comment]
@msdurex hi, it's been a few weeks. I just wanted to check whether you were able to try the troubleshooting step above.

**Comment by msdurex** [comment]
Sorry, The folder doesn't exist.
