### ISSUE TITLE
DEVICE_CLASS_HUMIDIFIER deprecation

### ISSUE THREAD

**Issue by RomanitoX** [libdyson-wg/ha-dyson#122]
Hi, is this possible to replace this constant by the new static call, thanks !

DEVICE_CLASS_HUMIDIFIER was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.HUMIDIFIER instead

**Comment by dotvezz** [comment]
Ahh looks like I missed this one in the last round of deprecation-prrofing. I'll get a release out that resolves it soon, thanks!

**Comment by dotvezz** [comment]
Resolved with [v1.3.10](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.3.10)
