### ISSUE TITLE
How to switch to heat mode?

### ISSUE THREAD

**Issue by thematrixdev** [libdyson-wg/ha-dyson#124]
Hello there.

I have HP07.

How to switch to heat / cool mode with this integration?

Thanks.

**Comment by thematrixdev** [comment]
I have found it.

![image](https://github.com/libdyson-wg/ha-dyson/assets/19472561/37c6d6d7-8839-4356-8303-9397637cf880)

**Comment by dotvezz** [comment]
Hey! Glad you found what you need. If you want a card on a dashboard, you can use a Thermostat card to control the heat mode as well.
