### ISSUE TITLE
2024.2 beta - new, logs 

### ISSUE THREAD

**Issue by Anto79-ops** [libdyson-wg/ha-dyson#128]
hey, looks like HA changes in 2024.2b0 have afffected Dyson again :( but not serious, just warnings:

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: 4:03:47 PM (4 occurrences)
Last logged: 4:03:51 PM

Entity None (<class 'custom_components.dyson_local.climate.DysonPureHotCoolEntity'>) implements HVACMode(s): off, cool, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by Anto79-ops** [comment]
ok, my Nexia Thermostat and Nest Thermostat also are giving the same erros BUT I was told that it will be fixed by this by release with this PR so perhaps this will also fix it for Dyson. Here's the PR:

https://github.com/home-assistant/core/pull/109250

**Comment by Anto79-ops** [comment]
the above PR got merged in b2, and it fixed my other thermostats (Nexia/Trane, Nest) but did not fix it for Dyson.

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:357
Integration: Climate (documentation, issues)
First occurred: 4:22:17 PM (2 occurrences)
Last logged: 4:22:18 PM

Entity None (<class 'custom_components.dyson_local.climate.DysonPureHotCoolEntity'>) implements HVACMode(s): off, cool, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by dotvezz** [comment]
Cool deal, thanks for the info! This is a quick fix so I'll get it taken care of soon.

**Comment by Anto79-ops** [comment]
Great. If you wanted to know more, I believe this is the blog post that talks about it:

https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

**Comment by dotvezz** [comment]
I was slow on this one, but it's done in https://github.com/libdyson-wg/ha-dyson/pull/136 and will be included in the next release!

Closing this thread, but we can definitely reopen if it isn't solved with the future release.

**Comment by Anto79-ops** [comment]
interesting, @dotvezz I'm still seeing this log on 2024.3. are you also seeing it?

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:361
integration: Climate (documentation, issues)
First occurred: 3:09:09 PM (3 occurrences)
Last logged: 3:09:15 PM

Entity None (<class 'custom_components.dyson_local.climate.DysonPureHotCoolEntity'>) implements HVACMode(s): off, cool, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by robinhood-code** [comment]
The issue still exists for me. I confirm I have v1.3.11 downloaded

`Entity None (<class 'custom_components.dyson_local.climate.DysonPureHotCoolLinkEntity'>) implements HVACMode(s): off, cool, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues`

![image](https://github.com/libdyson-wg/ha-dyson/assets/6055272/a3d7bb4c-9700-4994-a33f-895eef9d25e3)

**Comment by Anto79-ops** [comment]
correct. I'm still seeing it on 2024.6.0. Maybe we can re-open this issue?

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:371
integration: Climate (documentation, issues)
First occurred: June 5, 2024 at 1:10:52 PM (3 occurrences)
Last logged: June 5, 2024 at 1:10:58 PM

Entity None (<class 'custom_components.dyson_local.climate.DysonPureHotCoolEntity'>) implements HVACMode(s): off, cool, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by Anto79-ops** [comment]
just posting here from 2024.8.0bx, as the log message may have been updated:

```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 6:03:30 AM (10 occurrences)
Last logged: 6:03:33 AM

Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolLinkEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolLinkEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by dbdavid44** [comment]
Same issue for me:

<img width="1419" alt="iShot_2024-08-10_08 56 05" src="https://github.com/user-attachments/assets/1e6033f4-1dea-4419-a4f2-9f75d7306746">

**Comment by dotvezz** [comment]
@Anto79-ops yep, I opened #183 to track those new logs. (those are for FanEntityFeature, this original thread was for  ClimateEntityFeature so just trying to keep things separate and... sorta organized? :sweat_smile: )

For the original logs, the latest release ([v1.4.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.4.0)) _should_ finally resolve these silly logs. Please feel free to tell me I'm wrong if it doesn't though!

**Comment by Anto79-ops** [comment]
Thanks @dotvezz!  Btw, good to hear from you.

**Comment by dotvezz** [comment]
@Anto79-ops thanks! Gotta admit fatherhood has kept me busy hahaha.

**Comment by Anto79-ops** [comment]
@dotvezz oh yeah, that'll do it. Congratulations! Try to get some sleep 😴 haha
