### ISSUE TITLE
After install through HACS, nothing shows up

### ISSUE THREAD

**Issue by KLucky13** [libdyson-wg/ha-dyson#13]
After adding the repo and downloading (and restarting) nothing showed up. I tried the no longer supported "original" repo first and had the same issue, so I deleted that one, hoping this one would work but no cigar.

Any idea what might be going on? Basically nothing shows up in the integrations. I do see the files via the file editor, so it is installed.

**Comment by KLucky13** [comment]
I now also installed the cloud repo (was not intending to use that one), but same problem, nothing shows up in the integrations..

**Comment by KLucky13** [comment]
I'm an idiot, i did not realize i needed to add it to the integrations myself (pretty new to HA)..

**Comment by dotvezz** [comment]
Hey @KLucky13! I'm glad you were able to figure it out! You have my sympathy, HA can be super clunky and I remember needing to rewire my brain around what "an integration" means when I first started using it.
