### ISSUE TITLE
Air Quality Index? What Is The Scale?

### ISSUE THREAD

**Issue by jmo2610** [libdyson-wg/ha-dyson#132]
I have a DP01 air purifier. What is the scale for the air quality index entity? In the Dyson app, there's "good, fair, poor, very poor." My air quality index just says 3. I'm assuming that's a measurement of air quality. I just don't know what it means.

**Comment by dotvezz** [comment]
Unfortunately we don't really know the scale either. It's a value fed directly from the device. Previous versions of the mobile app displayed the number, but it seems the app only shows a graph with no labels.

The graph's X axis is linear to the index value. It looks like:

- 1 ~ 2.5 is good
- 2.5 ~ 4 is Fair
- 4 ~ 5.5 is Poor
- 5.5 ~ 7 is Very Poor
- 7 ~ 8 is Extremely Poor
- 9 ~ 10 is Extreme

**Comment by jmo2610** [comment]
Well this is certainly helpful. Thank you!

**Comment by dotvezz** [comment]
Happy to help! Sorry I can't give a more exact answer. Closing this now, but let me know if there's anything else I can help with!
