### ISSUE TITLE
Feature Request: Add ability to set preset mode and fan speed through automation.

### ISSUE THREAD

**Issue by myevit** [libdyson-wg/ha-dyson#134]
I am using automation to turn on and off my TP02. There is no option to set preset mode nor fan speed. Seems like essential feature is missing.

**Comment by dotvezz** [comment]
Hi @myevit! Both of these features should definitely be working. Can you check the Fan entity associated with your TP02? 

For reference, here's a screenshot for the Fan entity panel of my TP02.
![image](https://github.com/libdyson-wg/ha-dyson/assets/4571263/0444a72a-14e5-42bd-a98a-4145109ace83)

**Comment by myevit** [comment]
Hello. I have the control from UI, same as what is on your screenshot. What I am talking is automation. I couldn’t find the way to change presets or fan speed in the automation. 
for example. I have scheduled on and off time for the fan, but when it’s turning on it defaults to speed 1 manual. And I can switch it to auto in automation.

**Comment by benvezzani-telly** [comment]
Nice! Glad to hear it's working for you then. I recommend reading up on the fan entity documentation for Home Assistant, which provides the information you need for setting the fan speed.

https://www.home-assistant.io/integrations/fan/#service-fanset_percentage

Let me know if you have any more questions of course!

**Comment by dotvezz** [comment]
(Sorry for the double post, I accidentally commented from the wrong account previously)

Nice! Glad to hear it's working for you then. I recommend reading up on the fan entity documentation for Home Assistant, which provides the information you need for setting the fan speed.

https://www.home-assistant.io/integrations/fan/#service-fanset_percentage

Let me know if you have any more questions of course!

**Comment by myevit** [comment]
Ah. This is how. Thanks!
