### ISSUE TITLE
Missing VOC/ NO2 raw values

### ISSUE THREAD

**Issue by dustingrady** [libdyson-wg/ha-dyson#137]
Thanks so much for carrying on this project; Everything has worked for me so far. One thing I've noticed however is that there doesn't seem to be raw VOC or NO2 values, and instead the entities provides an index. 

I have a few alerts setup for the raw values, and the index seems to take into consideration changes over time, which I do not particularly need as I'm graphing all of that on HA already. 

Is there a way to expose the raw (non indexed) values?

**Comment by codyc1515** [comment]
When you say you have some alerts, are these with other non-Dyson devices?

For the large part, I believe this integration just exposes what you see in the app.

**Comment by dustingrady** [comment]
I looked up the acceptable tolerances for VOC/ NO2/ PM2.5/ PM10 from the EPA website, and they will say something along the lines of "avoid levels higher than X for more than 30 minutes". 

I set up automations in HA that will check those values and if they are above those limits for more than 30 minutes, it will alert me. When I only have access to the VOC or NO2 index values though, it makes it harder (or impossible) to compare to the EPA recommendations.

**Comment by dotvezz** [comment]
@dustingrady 

Hey, thanks for reporting! This is something that's come up a few times so I should probably update the FAQ on the readme. The short answer here is: while we're really grateful to Shen and the original set of contributors whose shoulders we're standing on here, the original VOC and NO2 sensors were incorrectly reporting µg/m³, when the sensor data from the device is actually an index. Unfortunately, the fan devices do not give us any raw sensor numbers, and we don't know the proprietary calculations that Dyson uses to turn their raw sensor data into the index value.

As a result, this integration has removed the old sensor.device_volatile_organic_compounds entities. We've implemented new sensor.device_volatile_organic_compounds_index entities that correctly reflect the data.

You can delete the old entities, which should now be unavailable, from your Home Assistant instance. And of course feel free to reply if you have any questions!

**Comment by dustingrady** [comment]
@dotvezz thank you for the reply! I'll reach out to Dyson (as futile as it may be) and ask how they are calculating this index.

**Comment by dustingrady** [comment]
@dotvezz looks like that is the case. Here is the reply from Dyson


For PM2.5 (2.5 micrometers), the following measurements (ug/m3) is the dividing scale:

Good: 0-35
Fair: 36-53
Poor: 54-70
Very Poor: 71-150
Extremely Poor: 151-250
Severe: 251+

PM 10 (10 micrometers) scale is also measured in (ug/m3):

Good: 0-50
Fair: 51-75
Poor: 76-100
Very Poor: 101-350
Extremely Poor: 351-420
Severe: 421+

The VOC and NO2 provide a grade from Good to Very Poor but it is not quantifiable.
