### ISSUE TITLE
Dyson fan humidity entity forwarded to homekit

### ISSUE THREAD

**Issue by liudger** [libdyson-wg/ha-dyson#148]
The previous version worked better with HomeKit. Not sure what changed. 
the previous version was shown in HomeKit as one device with clear gui. Now there are a few switches with no names and multiple devices. Fan and humidifier are separate devices. 

I’ll try to make some screenshots this week. Installing previous integration.

**Comment by RefineryX** [comment]
Does it look like the screenshots from this issue? 

https://github.com/libdyson-wg/ha-dyson/issues/70#issuecomment-1899173492

**Comment by dotvezz** [comment]
@liudger interesting, is Shen's version working but this one not? The structure and configuration of devices and entities should be identical, with one exception: We've updated the quality sensor entity units.

Other than air quality sensors being reported as an index instead of ppm, this should behave exactly the same as Shen's version. Can you help by describing or providing screenshots?

**Comment by liudger** [comment]
Yeah the current version looks like the other post. 

![IMG_4390](https://github.com/libdyson-wg/ha-dyson/assets/4112111/cbbd8fc0-570b-4e51-8a4a-fc04e78487cc)
![IMG_4391](https://github.com/libdyson-wg/ha-dyson/assets/4112111/151b1e65-f577-4bc3-91a0-0738889010ae)

I’ll do a revert tomorrow to  shen’s version and post it here

**Comment by dotvezz** [comment]
@liudger thanks, really appreciate your help debugging. If Shen's version works, that will be _weird_ but at least very informational.

**Comment by RefineryX** [comment]
This is not a new issue, this has heavily discussed here: https://github.com/libdyson-wg/ha-dyson/issues/70 along with screenshots of the old and current version…

**Comment by liudger** [comment]
Thank @RefineryX , This is indeed the issue I guess
![IMG_4400](https://github.com/libdyson-wg/ha-dyson/assets/4112111/e2faf982-1f39-4316-8fee-e67aca979f5f)
Old style control
