### ISSUE TITLE
Feature: support for Indoor Air Quality 

### ISSUE THREAD

**Issue by liudger** [libdyson-wg/ha-dyson#149]
Now the sensors of the fan measure separate components in the air. But it would be nice that it also combines these values as Indoor Air Quality. https://github.com/Limych/ha-iaquk/blob/dev/IAQ_Rating_Index.pdf

There is a component that does this.  
https://github.com/Limych/ha-iaquk

Integrating this inside dyson? Or should it be inside homeassistant and automatically calculate air quality. 

Why:
- easier to create automation based on air quality. No need to measure/trigger on multiple measurements. 
- easier to few the air quality in rooms.

**Comment by RedEarth1** [comment]
I think this has already been requested - #140

**Comment by dotvezz** [comment]
Yeah, I think this is the same as #140. It should be possible. With a young kid at home, I've been having difficulty finding time to add features to this project lately :sweat_smile:. I'll go ahead and mark this as closed, but I do not want you to think that more discussion is unwelcome! Feel free to follow up with anything at all!
