### ISSUE TITLE
Unable to discover Dyson Purifier Cool

### ISSUE THREAD

**Issue by brianqtb** [libdyson-wg/ha-dyson#153]
I installed the libdyson-wg add-on as per instruction. Successfully completed the process, by providing my email and dyson generated code. However I don't see any device discovered.
![Uploading Screenshot 2024-04-25 203316.jpg…]()

**Comment by dotvezz** [comment]
Hi @brianqtb! I see you also had opened #143. Is this the same device you were having trouble with before?

**Comment by dotvezz** [comment]
Closing this as well as #156, and reopening #143 to keep all the discussion in a single place.
