### ISSUE TITLE
Unable to complete the registration process of my Dyson Pure Cool purifier

### ISSUE THREAD

**Issue by brianqtb** [libdyson-wg/ha-dyson#156]
I power off the Dyson fan and turned on again. HA still cannot discover my dyson fan. How can I enable the logs?

**Comment by dotvezz** [comment]
@brianqtb I've noticed you're opening quite a few new issues over the past few weeks (#156, #153, #143). Is it okay if we keep the conversation on a single thread? Let's reopen #143 and close the others.
