### ISSUE TITLE
myDyson authentication stuck "already_in_progress"

### ISSUE THREAD

**Issue by cliaz** [libdyson-wg/ha-dyson#157]
Installed the integration via HACS, restarted HA, went to configure the integration / add the Dyson devices I have configured in the MyDyson app.

Chose the "Setup automatically with your MyDyson account" option, provide email, and get the following message![image](https://github.com/libdyson-wg/ha-dyson/assets/3636531/e2edf710-4c7f-45de-a640-3a7bbd262213)

Remains that way for a while.
Note: my email address has a '+' character in it, but does work for MyDyson registration / authentication

**Comment by cliaz** [comment]
It looks like it's an issue with handling special characters in emails, on the Dyson side of things. Despite being able to log in to their site, I couldn't change password, change email address, add / remove any devices.

I deleted that account entirely and recreated one using an email address without a '+' character in it, and your integration worked right away.

**Comment by dotvezz** [comment]
@cliaz As a fellow +tag user I can heavily sympathize.
