### ISSUE TITLE
Temperature value has too many decimal digits

### ISSUE THREAD

**Issue by savingprivatebryan** [libdyson-wg/ha-dyson#162]
I setup a TP7C Purifier Cool fan and although the temperature reading is accurate it's not pretty. It is showing 15 decimal digits which breaks it out into two lines. All other sensor data looks great.

I did notice the sensor entities took about a half hour to show up after setting up the device in HA but I'm assuming that's unrelated to the display of the temperature.
![image](https://github.com/libdyson-wg/ha-dyson/assets/6765837/b065771d-1171-4cb7-85a9-765a42184dfd)

**Comment by savingprivatebryan** [comment]
Apologies, just found #105 which this is a dupe of. I set the precision in the temperature entity and it looks great now.

**Comment by dotvezz** [comment]
Hey @savingprivatebryan! Glad you were able to get a solution working for you! And I appreciate you going through the trouble of opening the discussion too. Even though you were able to find a working fix on #105, stuff like this helps me keep track of issues people are seeing.
