### ISSUE TITLE
Add Support for Dyson VizNav

### ISSUE THREAD

**Issue by simplytoast1** [libdyson-wg/ha-dyson#163]
Requesting support for the Dyson VizNav as noted in the docs

**Comment by dotvezz** [comment]
Hi @simplytoast1! There's a couple of discussions already going on for the Vis Nav at this time:  #142,  #110 

There's also a pre-release which you can use to test with your device: https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.4.0-rc4

I'll close this discussion, but please feel free to go add your feedback to the other threads. Especially if you're able to help
