### ISSUE TITLE
Can not use Nitrogen Dioxide and Volatile Organic CompoundsI don’t know why..

### ISSUE THREAD

**Issue by iambbbb** [libdyson-wg/ha-dyson#164]
When I update to the latest version, it’s can not use Nitrogen Dioxide and Volatile Organic Compounds I don’t know why.. 
I tried restart reload and repair, still not working.
![IMG_0084](https://github.com/libdyson-wg/ha-dyson/assets/58380625/bd111a1e-dc25-4bd6-b264-b9a53d382b14)

**Comment by dotvezz** [comment]
Hi there @iambbbb This i
