### ISSUE TITLE
Not able to set swing mode via automation

### ISSUE THREAD

**Issue by lars-hh** [libdyson-wg/ha-dyson#172]
Hi,
<img width="576" alt="IMG_0596" src="https://github.com/libdyson-wg/ha-dyson/assets/154931328/d11c362a-b5d7-4ebe-9511-e1384e6e6cb7">

i usualy use the swing feature of the dyson fan. But it is not possible to active this feature via button or automation. The activation is only possible in this control button on the screenshot. 
The idea was to set: Dyson on > set night mode > Speed 8 > swing on

Right now i have to open the device in HA and active swing manuelly.

Thank you

**Comment by dotvezz** [comment]
@lars-hh you should be able to use the `enable_oscillation` and `disable_oscillation` service calls in your automations. Let me know if you have any trouble doing this though!

**Comment by dotvezz** [comment]
Marking this closed as you should be able to use the services described in my previous comment. Please feel free to reopen if you're having issues though!
