### ISSUE TITLE
Air Quality Index not present at all

### ISSUE THREAD

**Issue by aglasson** [libdyson-wg/ha-dyson#174]
My device in Home Assistant is completely missing the AQI metric which others seem to have available based on comments in other issues. I've tried refresshing device integration etc. but to no avail, everything else seems to work fine except this. Not sure if there is anything I can do myself to correct or if this is a bug that I need to wait to be fixed? Image of app showing that there is definitely AQI data for my device.
<img src="https://github.com/user-attachments/assets/1fa56d76-46b2-42db-aad1-3db8e45ec318" height="500"> <img src="https://github.com/user-attachments/assets/725952f9-719d-41f6-a765-11ee792a94a2" height="500">

**Comment by dotvezz** [comment]
Hi @aglasson!

We've got #140 for tracking this feature request. If you could hop over there that would be awesome! I'll close this issue to keep conversation in one place.
