### ISSUE TITLE
Switching to new integration has lost two sensors

### ISSUE THREAD

**Issue by snigehere** [libdyson-wg/ha-dyson#176]
Thanks for taking over this useful integration - I saw errors in my log about the version I had installed and decided to look what was happening.

I followed your clear guidance to remove the cloud and local version and installed the new ha-dyson version and that worked very well .. much easier than deleting the whole integration and starting over.

My device is a VS7 Dyson Purifier Cool Gen1

I notice I have two sensors hare no longer being updated 
sensor.<name>_volatile_organic_compounds
sensor.<name>_nitrogen_dioxide

I see a couple of sensors that have similar names
sensor.<name>_volatile_organic_compounds_index
sensor.<name>_nitrogen_dioxide_index
but I don't know if these are new (issue with 2024.8 core history data) but they are showing different info compared to the old sensor

![image](https://github.com/user-attachments/assets/47bb2061-034d-4b16-9392-5b10c0c18233)

Any guidance would be appreciated

**Comment by dotvezz** [comment]
Hi there @snigehere! This is actually expected. There's a LOT of reading in https://github.com/libdyson-wg/ha-dyson/issues/4 if you want the full context, and some additional summaries in https://github.com/libdyson-wg/ha-dyson/issues/89 and https://github.com/libdyson-wg/ha-dyson/issues/127.

The short answer here is: while we're really grateful to Shen and the original set of contributors whose shoulders we're standing on here, the original VOC and NO2 sensors were incorrectly reporting µg/m³, when the sensor data from the device is actually an index. Unfortunately, the fan devices do not give us any raw sensor numbers, and we don't know the proprietary calculations that Dyson uses to turn their raw sensor data into the index value.

As a result, this integration has removed the old sensor.device_volatile_organic_compounds entities. We've implemented new sensor.device_volatile_organic_compounds_index entities that correctly reflect the data.

You can delete the old entities, which should now be unavailable, from your Home Assistant instance. And of course feel free to reply if you have any questions!

**Comment by snigehere** [comment]
Hi Ben - Many thanks for the explanation - sorry I didn't spot the conversation - I searched open tickets but failed to search closed ones.  I didn't want to delete the sensors without knowing the issue but based on your explanation I have got rid of them.

Thanks again

**Comment by dotvezz** [comment]
Happy to help! Feel free to ping if you see any more issues.
