### ISSUE TITLE
Add support for Dyson 360 Vis Nav

### ISSUE THREAD

**Issue by ba-johnson** [libdyson-wg/ha-dyson#177]
Request is quite self explanatory so I don't want to add extra guff to complicate anything. It would be great to have Vis Nav support added to this integration!

**Comment by dotvezz** [comment]
@ba-johnson there's a discussion over in #142 if you'd like to help test the Vis Nav support! It's added to the latest release, but it's been available in pre-releases for testing for a while. Feel free to upgrade to either of those paths!

**Comment by dotvezz** [comment]
Marking as closed, just as an attempt to keep conversation for this on #142. Please do feel free to reply here or in that thread though!
