### ISSUE TITLE
no devices found using dyson account method

### ISSUE THREAD

**Issue by frank3101** [libdyson-wg/ha-dyson#180]
i add the integration， and setup automatically with my MyDyson Account, but there is no devices found in the integration. my device is HP04 dyson Pure Hot+Cool

**Comment by dotvezz** [comment]
Hi there @frank3101! This is interesting. I have another tool called [opendyson](https://github.com/libdyson-wg/opendyson) which can help to troubleshoot when devices aren't discoverable. Are you able to install it and run it with the `devices` argument? (On linux, `./opendyson devices`. On Windows, `opendyson.exe devices`, etc) and confirm whether your HP04 is found by the tool?

Note: You don't need to share sensitive information like IoT Credentials. For now, just confirming it is found (and maybe its firmware version) is enough. But we might want to come back and check other values later.

**Comment by dotvezz** [comment]
@frank3101 it's been a few weeks since the last message here. I hope your issue has been resolved, and am marking this closed. But please feel free to reply and reopen if you're still experiencing this problem!
