### ISSUE TITLE
Failed to Connect on TP09

### ISSUE THREAD

**Issue by harrynrobinson** [libdyson-wg/ha-dyson#181]
Attempting to connect three TP09 fans via the myDyson account. Home Assistant finds the devices and two were successfully added but one refuses to connect even with a static IP.

Fan is online and active in myDyson app.

Home Assistant is on v13 and the fan is running the latest firmware.
![IMG_0040](https://github.com/user-attachments/assets/3fd1f311-2cd5-4e60-a633-e5a62d2b8a83)

**Comment by dotvezz** [comment]
Hi @harrynrobinson! TP09s often have connectivity problems that are resolved by power-cycling the problematic device. Could you confirm whether power-cycling (unplug and plug back in) helps get this device connected?

**Comment by harrynrobinson** [comment]
Darn, of course that did work.

Sorry for not just trying this first. Thank you for the integration, it’s the reason I purchased the TP09s.
