### ISSUE TITLE
Support for more than one Dyson Fan.

### ISSUE THREAD

**Issue by Tacmatricx** [libdyson-wg/ha-dyson#185]
Hi,

I have two Dyson Purifier Hot+Cool devices in different zones. I was able to add my account and the first fan easily (great work by the way! Love this integration!). To add a second device, I had to remove my account (it said the account was already added when I tried to add it again) and when I was able to add the account again without deleting the first fan, it picked up the second fan. However even though the first fan is now listed along with the second, I am not able to control or monitor the first fan.

Cheers!

Chris

**Comment by Tacmatricx** [comment]
Fixed I think, I managed to do a remove and manual add of the second fan (was actually picked up by home assistant when I removed it) and both seem to be working together at the moment. Might be easier to check for multiple fans when the account is added or give the option to add a fan using an existing account?

**Comment by dotvezz** [comment]
Hi @Tacmatricx. When you add your account, it already does scan and auto-setup _all_ fans attached to the account, including multiple of the same model. You don't need to remove or manually add fans. I have a tool for troubleshooting issues like this, if you'd like to help identify the issue.

It's called opendyson, and can be run from a command line. Feel free to download the version that fits your OS/CPU over here: https://github.com/libdyson-wg/opendyson/releases.

Once you have it, run it with the `devices` argument. So if you're on linux, it'd be `./opendyson devices`. You'll be prompted through the login process and it will display all the information it's able to find about your devices. Feel free to share the result here (please make sure to omit the IoT credentials and other sensitive information before sharing though).

**Comment by dotvezz** [comment]
Marking closed as multiple fans is fully supported, but please feel free to continue the conversation! I'm happy to answer any questions or help with troubleshooting your setup!
