### ISSUE TITLE
Stacktrace when adding type 520 Pure Cool Desk

### ISSUE THREAD

**Issue by thewishy** [libdyson-wg/ha-dyson#19]
- Advanced install (not HA OS)
- Python 3.10
- Having trouble adding model 520
- Model 527 works correctly (From previous shenxn release)
- libdyson_neon-1.0.2  is latest from pip (0.8.11)
- Dyson_local v0.19.0

Adding the model 520 Pure Cool Desk results in a stacktrace. The device appears in the integrations list, but no data and no button. 

I've done a packet capture on the JSON being passed across MQTT. I don't see cflr (carbon filter life) being passed across. Also in the official Dyson mobile app it shows as "This feature in temporarily unavailable" for filter status, although on the display on the fan itself I can see it seems to have some filter data.

MQTT Updates
`520/VW1-UK-MAA3485B/command{"msg": "REQUEST-CURRENT-STATE", "time": "2023-05-06T13:55:29Z"}0w..520/VW1-UK-MAA3485B/command{"msg": "REQUEST-PRODUCT-ENVIRONMENT-CURRENT-SENSOR-DATA", "time": "2023-05-06T13:55:29Z"}.....0..."520/VW1-UK-MAA3485B/status/current{"msg":"CURRENT-STATE","time":"2023-05-06T13:55:29.000Z","mode-reason":"PRC","state-reason":"NONE","dial":"OFF","rssi":"37","product-state":{"fpwr":"ON","fdir":"OFF","auto":"OFF","fnsp":"0002","qtar":"0001","sltm":"OFF","oson":"OFF","nmod":"OFF","rhtm":"ON","fnst":"FAN","filf":"0000","ercd":"NONE","wacd":"NONE"},"scheduler":{"srsc":"0000","dstv":"0000","tzid":"0000"}}0..."

520/VW1-UK-MAA3485B/status/current{"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2023-05-06T13:55:30.000Z","data":{"tact":"2971","hact":"0055","pm25":"0000","pm10":"0000","va10":"0004","noxl":"0001","p25r":"0000","p10r":"0000","sltm":"OFF"}}0..."520/VW1-UK-MAA3485B/status/current{"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2023-05-06T13:55:30.000Z","data":{"tact":"2971","hact":"0055","pm25":"0000","pm10":"0000","va10":"0004","noxl":"0001","p25r":"0000","p10r":"0000","sltm":"OFF"}}0..."

520/VW1-UK-MAA3485B/status/current{"msg":"CURRENT-STATE","time":"2023-05-06T13:55:30.000Z","mode-reason":"PRC","state-reason":"NONE","dial":"OFF","rssi":"36","product-state":{"fpwr":"ON","fdir":"OFF","auto":"OFF","fnsp":"0002","qtar":"0001","sltm":"OFF","oson":"OFF","nmod":"OFF","rhtm":"ON","fnst":"FAN","filf":"0000","ercd":"NONE","wacd":"NONE"},"scheduler":{"srsc":"0000","dstv":"0000","tzid":"0000"}}"

520/VW1-UK-MAA3485B/status/current{"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2023-05-06T13:55:31.000Z","data":{"tact":"2971","hact":"0055","pm25":"0000","pm10":"0000","va10":"0004","noxl":"0001","p25r":"0000","p10r":"0000","sltm":"OFF"}}"

520/VW1-UK-MAA3485B/status/current{"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2023-05-06T13:55:31.000Z","data":{"tact":"2971","hact":"0055","pm25":"0000","pm10":"0000","va10":"0004","noxl":"0001","p25r":"0000","p10r":"0000","sltm":"OFF"}}`

`May 06 15:20:03 nandi hass[1485197]: 2023-05-06 15:20:03.597 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up dyson_local platform for sensor
May 06 15:20:03 nandi hass[1485197]: Traceback (most recent call last):
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
May 06 15:20:03 nandi hass[1485197]:     await asyncio.shield(task)
May 06 15:20:03 nandi hass[1485197]:   File "/home/homeassistant/.homeassistant/custom_components/dyson_local/sensor.py", line 68, in async_setup_entry
May 06 15:20:03 nandi hass[1485197]:     if device.carbon_filter_life is None:
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/libdyson/dyson_pure_cool.py", line 48, in carbon_filter_life
May 06 15:20:03 nandi hass[1485197]:     return int(filter_life)
May 06 15:20:03 nandi hass[1485197]: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

May 06 15:20:03 nandi hass[1485197]: 2023-05-06 15:20:03.599 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform dyson_local
May 06 15:20:03 nandi hass[1485197]: Traceback (most recent call last):
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
May 06 15:20:03 nandi hass[1485197]:     await asyncio.gather(*tasks)
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
May 06 15:20:03 nandi hass[1485197]:     await entity.add_to_platform_finish()
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
May 06 15:20:03 nandi hass[1485197]:     self.async_write_ha_state()
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
May 06 15:20:03 nandi hass[1485197]:     self._async_write_ha_state()
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 635, in _async_write_ha_state
May 06 15:20:03 nandi hass[1485197]:     attr.update(self.extra_state_attributes or {})
May 06 15:20:03 nandi hass[1485197]:   File "/home/homeassistant/.homeassistant/custom_components/dyson_local/fan.py", line 231, in extra_state_attributes
May 06 15:20:03 nandi hass[1485197]:     ATTR_ANGLE_LOW: self.angle_low,
May 06 15:20:03 nandi hass[1485197]:   File "/home/homeassistant/.homeassistant/custom_components/dyson_local/fan.py", line 220, in angle_low
May 06 15:20:03 nandi hass[1485197]:     return self._device.oscillation_angle_low
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/libdyson/dyson_pure_cool.py", line 130, in oscillation_angle_low
May 06 15:20:03 nandi hass[1485197]:     return int(self._get_field_value(self._status, "osal"))
May 06 15:20:03 nandi hass[1485197]: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

May 06 15:20:03 nandi hass[1485197]: 2023-05-06 15:20:03.609 ERROR (MainThread) [homeassistant.components.fan] Error while setting up dyson_local platform for fan
May 06 15:20:03 nandi hass[1485197]: Traceback (most recent call last):
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
May 06 15:20:03 nandi hass[1485197]:     await asyncio.gather(*pending)
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
May 06 15:20:03 nandi hass[1485197]:     await asyncio.gather(*tasks)
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
May 06 15:20:03 nandi hass[1485197]:     await entity.add_to_platform_finish()
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
May 06 15:20:03 nandi hass[1485197]:     self.async_write_ha_state()
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
May 06 15:20:03 nandi hass[1485197]:     self._async_write_ha_state()
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 635, in _async_write_ha_state
May 06 15:20:03 nandi hass[1485197]:     attr.update(self.extra_state_attributes or {})
May 06 15:20:03 nandi hass[1485197]:   File "/home/homeassistant/.homeassistant/custom_components/dyson_local/fan.py", line 231, in extra_state_attributes
May 06 15:20:03 nandi hass[1485197]:     ATTR_ANGLE_LOW: self.angle_low,
May 06 15:20:03 nandi hass[1485197]:   File "/home/homeassistant/.homeassistant/custom_components/dyson_local/fan.py", line 220, in angle_low
May 06 15:20:03 nandi hass[1485197]:     return self._device.oscillation_angle_low
May 06 15:20:03 nandi hass[1485197]:   File "/srv/homeassistant/lib/python3.10/site-packages/libdyson/dyson_pure_cool.py", line 130, in oscillation_angle_low
May 06 15:20:03 nandi hass[1485197]:     return int(self._get_field_value(self._status, "osal"))
May 06 15:20:03 nandi hass[1485197]: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
`

**Comment by dotvezz** [comment]
Thanks for the report! Interesting result you've got here. It shouldn't be difficult to fix, but I'm actually worried that I've gone and caused this myself. I know I've modified the `_get_field_value` method in libdyson ([link to the commit and lines in question](https://github.com/libdyson-wg/libdyson-neon/commit/8d0e49e8f4d170855209f8328032dfcdd2f288b9#diff-8cbc4694ccbe6f703e6c6d6fa63ffb7e011b5fee33028e4ecf5b1828388e8621R290-R293)). 

Would you be willing to test your setup on shenxn's repo and see if it works or not?

Either way, I'll work on an update for you.

**Comment by mundschenk-at** [comment]
It's widespread issue with 2023.05.x, don't feel bad about it. I have linked to the solution in the other issue.

**Comment by dotvezz** [comment]
Aha, okay that makes me feel better. I'll do some cleanup of the areas where we're relying on `int()` in libdyson and the integration.

**Comment by thewishy** [comment]
I'm still running 2023.04. 

The issue was the same under the shenxn version of the repo, hence I upgraded in the hope the issue would be resolved, so nothing you've done :)

**Comment by dotvezz** [comment]
Aha gotcha, I'll take that too! Better a bug I inherited than a bug I created :smile:

I'll get to working on a fix for you - basically it'll act like the new logic for Formaldehyde sensors and check if it exists before adding the entity.

**Comment by dotvezz** [comment]
@thewishy [v0.21.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.21.0) is released which should hopefully take care of this for you.

**Comment by thewishy** [comment]
So, interestingly, dyson dropped a firmware update on the fan. The previously unavailable filter information started displaying in the app, and I retried setup in HA.
Good news is that it's working brilliantly. Bad news is, I can't reproduce the problem for others, so I guess it makes sense to close the issue?

**Comment by dotvezz** [comment]
Know what? I'll take the "blame dyson" route you've so generously presented! Closing for now, but by all means feel free to follow up if you see it again. I'll happily give it the proper treatment.
