### ISSUE TITLE
Can't Add Fan Slider To Dashboard

### ISSUE THREAD

**Issue by RAiDX0r** [libdyson-wg/ha-dyson#194]
How do I add the fan slider to the dashboard?  I can add the following Fan and Climate Control widgets.  But I can't add the fan slider that shows up when you drilldown into the fan widget.

![image](https://github.com/user-attachments/assets/0b511677-39b8-49f3-a744-81ae19b3119d)

![image](https://github.com/user-attachments/assets/a88c686d-7330-458a-9c90-486e2579972b)

**Comment by dotvezz** [comment]
@RAiDX0r there are a couple of options, but annoyingly I think they all require custom cards. For some reason, as far as I know, the slider from the Fan Entity expanded view is not available as a default card.

- Custom cards that I use:
  - [Slider Button Card](https://github.com/mattieha/slider-button-card)
  - [Air Purifier Card](https://github.com/denysdovhan/purifier-card)

**Comment by RAiDX0r** [comment]
> @RAiDX0r there are a couple of options, but annoyingly I think they all require custom cards. For some reason, as far as I know, the slider from the Fan Entity expanded view is not available as a default card.
> 
> * Custom cards that I use:
>   
>   * [Slider Button Card](https://github.com/mattieha/slider-button-card)
>   * [Air Purifier Card](https://github.com/denysdovhan/purifier-card)

Thank you very much!  I will try these out.

**Comment by RedEarth1** [comment]
You can add a tile card, select your fan as the entity and then you should be able to add "fan speed" as a feature.

**Comment by dotvezz** [comment]
@RedEarth1 that's awesome, I had no idea!

**Comment by RedEarth1** [comment]
You can add preset mode buttons as a feature too, but unfortunately there's no option to add title buttons for the oscillate and reverse modes...yet
