### ISSUE TITLE
Integration stopped working, not sure how to troubleshoot

### ISSUE THREAD

**Issue by Vortec4800** [libdyson-wg/ha-dyson#196]
I'm running HA 2024.10.2, HACS 2.0.1, and Dyson 1.4.2. I set the integration up this morning and it all worked great, but I rebooted my HA instance in the afternoon and ever since then, all my Dyson entities show as Unavailable and nothing works now. The device I'm trying to control is an air purifier and it's using my Dyson account.

I'm sure this isn't enough information to go by, how can I gather logs or something to help discover what the issue is?

**Comment by timogoudzwaard** [comment]
@Vortec4800 The same happened to me. I was able to fix it by going to settings > integrations > Dyson and clicking on the 3 dots to remove the entity and login. And then I pressed the 'add item' button on the same page, I logged in again and added the device. 

This sadly meant I had to change the cards in my dashboard to use the new entity. After doing that, everything works fine again.

**Comment by dotvezz** [comment]
@Vortec4800 you can enable debug logs and share them here. Home Assistant has an awesome page about how to do this on their site: https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics

**Comment by m0rph3usX** [comment]
Hey there, I am having the same problem.
I have a Dyson 360 Vis Nav and it was working 2-3 month ago, meaning, it was discovered and configured in this dyson integration. After my holiday I recognized that the dyson implementation was not anymore properly.
There was no connection to my Dyson.

So as @timogoudzwaard said, I removed every entries. Signed in again with my dyson account - no problem. So my Dyson got also discovered "H8T-EU-SHAXXXXA". So in the dyson implementation site, I click on the discovered dyson and "configure" button.

I enter the IP "192.168.178.104" (which I also can ping successfully) and after a while I get the message:
"Failed to connect. The IP Address may be required if your Home Assistant installation is running in a Container or a VM."


My Setup:
Rpi5 8GB:

Home Assistant:
Core 2024.10.3
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.3
Dyson 1.4.2

Dyson Firmware: RB03PR.01.08.003.4123

Also here my log:
[home-assistant_dyson_local_2024-10-24T21-02-26.046Z.log](https://github.com/user-attachments/files/17512857/home-assistant_dyson_local_2024-10-24T21-02-26.046Z.log)

**Comment by daknightuk** [comment]
> Hey there, I am having the same problem. I have a Dyson 360 Vis Nav and it was working 2-3 month ago, meaning, it was discovered and configured in this dyson integration. After my holiday I recognized that the dyson implementation was not working anymore properly - meaning there was no connection to my Dyson via this implementation.
> 
> So as @timogoudzwaard said, I removed every entries. Signed in again with my dyson account - no problem. So my Dyson got also discovered "H8T-EU-SHAXXXXA". So in the dyson implementation site, I click on the discovered dyson and "configure" button.
> 
> I enter the IP "192.168.178.104" (which I also can ping successfully) and after a while I get the message: "Failed to connect. The IP Address may be required if your Home Assistant installation is running in a Container or a VM."
> 
> My Setup: Rpi5 8GB:
> 
> Home Assistant: Core 2024.10.3 Supervisor 2024.10.3 Operating System 13.2 Frontend 20241002.3 Dyson 1.4.2
> 
> Dyson Firmware: RB03PR.01.08.003.4123
> 
> Also here my log: [home-assistant_dyson_local_2024-10-24T21-02-26.046Z.log](https://github.com/user-attachments/files/17512857/home-assistant_dyson_local_2024-10-24T21-02-26.046Z.log)

Refer to https://github.com/libdyson-wg/ha-dyson/discussions/142
Dyson turned off local MQTT

**Comment by dotvezz** [comment]
@m0rph3usX unfortunately the connection we use to Viz Nav products was disabled by Dyson, and as far as I know there's no way to reopen it. Your issue is unfortunately different from the one this thread is about.

**Comment by dotvezz** [comment]
@Vortec4800 were you able to get your setup working, or get debug logs enabled? For reference, here's my comment from a few weeks ago that should hopefully help get logging set up: https://github.com/libdyson-wg/ha-dyson/issues/196#issuecomment-2420754341

**Comment by Vortec4800** [comment]
Thanks for posting that. I've been out of town for a couple weeks and just came back to look into this more, and now the plugin is working normally. So that's great! But not super helpful for identifying a possible issue.

I'm going to close this out for now and consider it taken care of now that I have good instructions on enabling logging, so if it happens again I can do that and post something helpful.
