### ISSUE TITLE
Unable to add Pure Cool fan

### ISSUE THREAD

**Issue by pathofleastresistor** [libdyson-wg/ha-dyson#197]
I recently purchased a new Dyson Fan (model: TP07, type: 438K). The fan hasn't been discovered after using the MyDyson method.

I also tried the manual add method. I received an error suggesting I add the IP address. I wasn't sure how to find it across the many devices connected to my wifi.

I also tried the OpenDyson tool to listen to the MQTT service, but it also errored out with "Error: unable to get ip address".

My old TP07, 438E fan works just fine with HA, so I'm not sure how to proceed here. Any suggestions on how to troubleshoot?

**Comment by dotvezz** [comment]
@pathofleastresistor unfortunately the first thing we'll need to do is get the IP address of the fan and try to use it. Both the integration and Opendyson use [Zero-configuration networking](https://en.wikipedia.org/wiki/Zero-configuration_networking) features built into the fan to discover it on your LAN. If that doesn't work, we'll need to manually bypass the discovery step.

**Comment by dotvezz** [comment]
@pathofleastresistor Hey, just wanted to check and see if you saw the message from a few weeks ago! I hope you were able to get your setup working, and I'll close this topic. If you're still having issues, please feel free to reopen it so we can troubleshoot!

**Comment by pathofleastresistor** [comment]
Thanks! After finding the IP, the manual method did work. I never got the MyDyson method to work.
