### ISSUE TITLE
TP09 not detected via MyDyson

### ISSUE THREAD

**Issue by RobVyK** [libdyson-wg/ha-dyson#198]
Hi, I'm new to HA and am trying to add my Dyson Purifier Cool Formaldehyde (TP09) to it.
The device does not have a Wi-Fi sticker, so tried to use the MyDyson account.
I can connect with the account but it displays "No devices or entities", even though the device is properly registered in my account.

![image](https://github.com/user-attachments/assets/dce8ba4b-b92a-42fe-b4bb-c9308b431c8c)

![image](https://github.com/user-attachments/assets/0fea4ff4-4e0d-4bbb-b98e-03ad809221bb)

Any ideas how to make this work?
I'm not familiar with using python so if possible, I'd like to avoid the "manual" setup method.

Thanks!

**Comment by dotvezz** [comment]
Hi @RobVyK! While it's not currently documented very well, there's an alternative to the python code for the manual setup. It's called opendyson, and can be run from a command line. Feel free to download the version that fits your OS/CPU over here: https://github.com/libdyson-wg/opendyson/releases.

Once you have it, run it with the `devices` argument. So if you're on linux, it'd be `./opendyson devices`. You'll be prompted through the login process and it will display all the information it's able to find about your devices. Feel free to share the result here (please make sure to omit the IoT credentials and other sensitive information before sharing though).

**Comment by RobVyK** [comment]
Hi @dotvezz.
I tried opendyson (the Windows version) and it only returned data from a Dyson V15 vacuum cleaner I have. No reference to the TP09 purifier.
![image](https://github.com/user-attachments/assets/1c1d03d2-c0e2-4d51-9717-6c9df2399473)

This made me realize that it seems I have 2 different accounts (exactly same credentials) but in different regions.
The V15 is registered on "DE", while the TP09 is registered on "RO".

opendyson doesn't ask for the Region Code during login and somehow seems to default to my "DE" version of the account. I couldn't find a way to switch it to the "RO" account.

I tried also libdyson-neon, but after entering all the requested information it does not return anything.
![image](https://github.com/user-attachments/assets/ee9e6c6d-41e5-4f3e-8aba-4665b397979a)

If this is normal for "no devices" then it'd match the behavior of ha-dyson which is also not detecting any smart devices when selecting the country "RO".

Will try next to remove the TP09 from the "RO" region/account and re-register it into the "DE" region/account. Hopefully that'll help. Will let you know how it goes.

**Comment by RobVyK** [comment]
After registering the purifier in region "DE" everything started to work as expected. 😊
The device is detected automatically:
![image](https://github.com/user-attachments/assets/cbceee15-7532-4e5c-a493-64d7576931c6)

Looks like for some reason there are issues with detecting devices registered to "RO" region.
