### ISSUE TITLE
Info/pinout about internal Dyson Wifi modules?

### ISSUE THREAD

**Issue by floe** [libdyson-wg/ha-dyson#202]
I'm aware my question is a bit offtopic, but this might still be the right community to know.

Most Dyson devices supported by `ha-dyson` seem to be using the same Wifi module for connecting to the outside world, codenamed `DBWIFIBLE01` (see [1], possibly with Dyson part numbers 967473-01 and/or 967430-01).

This module also uses the same 8-pin connector in every Dyson product, and I'd be interested in figuring out the pinout of this connector in order to log the internal communication between the mainboard and the Wifi module. Would anyone around here happen to know some more details?

[1] https://usermanual.wiki/Dyson-Technology/DBWIFIBLE01-3718155.pdf

**Comment by dotvezz** [comment]
That's fascinating! Unfortunately, it looks like the doc you provided is one that's not intended to be in public circulation.

> DYSON CONFIDENTIAL INFORMATION
> This document and the copyright in it are the sole property of Dyson Technology Limited.
> The document and its contents are confidential and may not be reproduced, disclosed or
> used without the prior written consent of Dyson Technology Limited.

There's lots of really cool stuff, but in the interest of continuing to provide a good integration for HA users, one of my goals here is to _not_ find myself in Dyson lawyers' crosshairs. To that end, as grateful as I am for you offering it for some very cool reading, it's not something that I can safely apply whilst trying to perform that balancing act.

I'm closing this issue here just for housekeeping, but please feel free to follow up in this thread if you have any questions or concerns!

**Comment by floe** [comment]
I don't think you need to worry about Dyson's legal department - the document I linked was published as part of the FCC certification of this module, it's e.g. also on https://fccid.io/QVHDBWIFIBLE01 . But I understand that this isn't directly related to your HA integration, obviously - just wondering if there are folks around here who may already have had a more detailed look at the hardware.

**Comment by dotvezz** [comment]
@floe I totally understand where you're coming from. Perhaps I'm being overly cautious, but even if any use is legally defensible, I'm just one guy and Dyson is a multinational corporation.

For context here:

- One other member of the community here is already in direct contact with Dyson regarding a statement on regulatory compliance that may draw attention our way for several reasons.
-  To boot, there's been a significant recent uptick in Home Assistant integration projects getting shot down by corporate lawyers.
    - https://community.home-assistant.io/t/haier-hits-home-assistant-plugin-dev-with-takedown-notice-lets-fork/675784
    - https://www.home-assistant.io/blog/2023/10/13/removal-of-mazda-connected-services-integration/
    - https://www.home-assistant.io/blog/2023/11/06/removal-of-myq-integration/


So I'm choosing to maintain the status quo as much as possible. My goal here is very much not to do anything that could threaten this integration's co-existence with the big scary bear.
