### ISSUE TITLE
Find local username and password after cloud setup

### ISSUE THREAD

**Issue by chrish987** [libdyson-wg/ha-dyson#203]
I have the integration working after using the dyson account setup method. My device has no wifi sticker.

Is there a way to find the credentials after the setup has been completed? (so I am not reliant on the dyson account in the future).

**Comment by mundschenk-at** [comment]
In the HA `storage` folder, yes.

**Comment by dotvezz** [comment]
@chrish987 you can also use [opendyson](https://github.com/libdyson-wg/opendyson/tree/main) to get device credentials.

Closing the thread here, but feel free to follow up if you have any questions!
