### ISSUE TITLE
ha-dyson failing with "cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson'"

### ISSUE THREAD

**Issue by aburow** [libdyson-wg/ha-dyson#36]
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 12:27:43 PM (2 occurrences)
Last logged: 12:27:47 PM

Setup failed for custom integration dyson_cloud: Unable to import component: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.11/site-packages/libdyson/init.py)
Setup failed for custom integration dyson_local: Unable to import component: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.11/site-packages/libdyson/init.py)

**Comment by aburow** [comment]
Restarted the machine today and both dyson cloud and dyson local, as well as all devices I had on the system aren't available. The issue appears to be related to the above error.

**Comment by dotvezz** [comment]
Hey, sorry for the slow reply!

What's the version of ha-dyson you're using? 

> cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.11/site-packages/libdyson/init.py)

^ This is referencing `site-packages/libdyson` which is no longer used by this integration as of version v0.20.1.

**Comment by aburow** [comment]
I'm not sure now, I was sure I deleted the old version and added this one. Easy enough as I'm running on a vm.

**Comment by aburow** [comment]
I figured out what I did.

I had both the new and old github repo pages open and because they are so similar I lost track where I was copying links from when I setup the "new" integration. I nearly did the same thing again today. PEBKAC error on my end.

**Comment by dotvezz** [comment]
Glad to hear it's all figured out! I'll close the issue for now, but feel free to post if you have any more issues or questions.
