### ISSUE TITLE
Add the note about IP address to the README

### ISSUE THREAD

**Issue by ibielopolskyi-godaddy** [libdyson-wg/ha-dyson#5]
When you connect to the app and then attempt to retrieve credentials via get_devices.py, if you are on different networks (i.e. your phone is on mobile), you will get "Unable to authenticate user" error.

Once you login on the same network, it will work as expected.

**Comment by dotvezz** [comment]
This should be resolved by the latest release! Marking as closed, but I'll still monitor for replies and reopen if needed!
