### ISSUE TITLE
HA only recognises one device even I have two fans linked to my Dyson account

### ISSUE THREAD

**Issue by okamaokama** [libdyson-wg/ha-dyson#56]
I owned a dyson purifier cool formaldehyde and purifier hot+cold. The later one cannot show up in HA

**Comment by dotvezz** [comment]
Interesting, that should definitely not be happening. Are you able to run the get_devices.py script in [libdyson-neon](https://github.com/libdyson-wg/libdyson-neon)? The output of that script will be very helpful! Here's a quick example for how to use it.

```
Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: US
Email: dotvezz@gmail.com
Password: 
Verification code: 421114

Serial: N9R-US-PJB0000A
Name: 
Device Type: 527
Credential: [REDACTED]

Serial: NM7-US-REA0000A
Name: Downstairs
Device Type: 475
Credential: [REDACTED]

Serial: NM7-US-REA0000A
Name: Dyson Fan
Device Type: 475
Credential: [REDACTED]

Serial: X3V-US-RKA0000A
Name: Dyson Purifier Hot+Cool™
Device Type: 527K
Credential: [REDACTED]

```

Let me know if you have any questions! Happy to help.

**Comment by okamaokama** [comment]
That was solved after I installed the ha Dyson cloud integration. Don’t know why but it works now, thanks! Is it normal that the heat function is not functional through HomeKit?
