### ISSUE TITLE
Continuous Monitoring (Auto) switch not working for HP04

### ISSUE THREAD

**Issue by kramttocs** [libdyson-wg/ha-dyson#57]
Thanks for maintaining this.
I have an HP02 that I've had for a month and hooked it up using the original integration via the local mode by capturing the packets on my android phone. All has worked well. This was added under Device Type:  Pure Hot+Cool Link

Yesterday I got an HP04 and originally hooked it up via the original integration (didn't know about yours).
I did the same packet capture but it would only add using Pure Hot+Cool. So not the LINK one.
All works except for the Continuous Monitoring switch. It has no effect.

I found out about this integration and did the hot swap over. Still didn't work so removed the HP04 and readded but same behavior.

Is there something I can provide to help identify why this switch isn't working?
And is the HP04 being the Pure Hot+Cool expected vs the Pure Hot+Cool Link of the HP02?

**Comment by kramttocs** [comment]
Well this is embarrassing 😄 
You nailed it - it's not behaving like I [wrongly] expected.
I had in my head that Continuous Monitoring was the equivalent of Auto and thought (again, incorrectly) that switching it on the HP02 impacted the Auto mode. I see now that Auto is a preset under the fan. 

So nothing to see here 😉 

I do appreciate the explanation and background you provided.

**Comment by dotvezz** [comment]
> Well this is embarrassing smile
> You nailed it - it's not behaving like I [wrongly] expected.

You've got nothing to be embarrased about! Glad it's working!
