### ISSUE TITLE
Error fetching environmental data: Failed to request environmental data

### ISSUE THREAD

**Issue by RedNo7** [libdyson-wg/ha-dyson#59]
Hi,

I found this entry in my logs.  There is nothing before or after, just this one:
```yaml
2023-07-31 10:12:43.304 ERROR (MainThread) [custom_components.dyson_local] Error fetching environmental data: Failed to request environmental data
```

Both Dyson's are  online, but switched `off` so the environmental entities are all `unknown`.

Honestly, not much to go on, but I thought I'd report it as it may be a useful data point in the future.

Versions:
- HA `Home Assistant Container`, `core-2023.7.3`
- HACS `1.32.1`
- Dyson_local: `1.01`

**Comment by dotvezz** [comment]
Well that's weird! Let me know if it pops up again, we can try to identify some kind of pattern. I can't really prioritize it until we can learn more, but, I'll keep the issue open long-term for discussion and information sharing.

Thanks!

**Comment by RedNo7** [comment]
will do - cheers.

**Comment by Anto79-ops** [comment]
I get this sometimes and believe it means that your machine lost wifi or communication to HA.

You can try unplugging it to test.

**Comment by RedNo7** [comment]
> believe it means that your machine lost wifi or communication to HA

They were online and controllable

**Comment by Anto79-ops** [comment]
Yes,  I meant it could also be temporary disconnect and then it reconnects.

**Comment by RedNo7** [comment]
sorry!  ...I totally misunderstood.

**Comment by dotvezz** [comment]
Hopefully this isn't premature; I'm going to go ahead and close this issue as it seems like it hasn't repeated. @RedNo7 If you feel we should reopen, feel free to let me know.

**Comment by robinhood-code** [comment]
I have exactly the same issue, here is my log:

```This error originated from a custom integration.
Logger: custom_components.dyson_local
Source: helpers/update_coordinator.py:350
integration: Dyson ([documentation](https://github.com/libdyson-wg/ha-dyson), [issues](https://github.com/libdyson-wg/ha-dyson/issues))
First occurred: March 11, 2024 at 8:11:47 PM (78 occurrences)
Last logged: 11:17:10 AM 

Error fetching environmental data: Failed to request environmental data```

So it happened 78 times in 12 hours so the error is throwing out fairly regularly for me.

I thought it was related to the "continuous monitoring" function of my fan for air quality info but after disabling the option I still keep receiving the error so the error should be for something else. 

The fan is controllable in HA as well as the Dyson app. 

Happy to do further troubshooting if needed.
