### ISSUE TITLE
Unknown error. 

### ISSUE THREAD

**Issue by KINGLIFER** [libdyson-wg/ha-dyson#6]
When using the cloud after email the app returns Unknown error occurred
'\

**Comment by dotvezz** [comment]
> My question is how does this connect because Dyson sends a code you must add to login.

The first step in the libdyson login process is to get your Region and Email. It sends it to the dyson app API, which sends the email with the login code.

Dyson's login is... strange. The current implementation in libdyson was implemented by shenxn back in 2021. The Dyson API it goes through isn't officially documented as far as I'm aware, so it's going to be some reverse-engineering work to figure out how to fix long-lived bug on libdyson.

**Comment by dotvezz** [comment]
I've been doing some reverse-engineering of the Dyson API, and I think I have a solution. I'll be doing some testing tonight to be sure it works.

**Comment by dotvezz** [comment]
@KINGLIFER I've released an update to the cloud integration. Feel free to update in HACS and let me know if your issue continues.

**Comment by ChienTingLu** [comment]
I was encountering the same issue, the newest update fixed the problem perfectly. 
Thank you sooo much! @dotvezz

**Comment by fmonday** [comment]
Is there a beta version that I'm not seeing? I'm getting the `DysonInvalidAuth` error on version 0.17.0

**Comment by fmonday** [comment]
Interestingly I also tried using `get_devices.py` and that also yields the same error

**Comment by ChienTingLu** [comment]
The newest version is 0.17.2. 
Check it out in the releases page.

**Comment by fmonday** [comment]
The current version of ha-dyson is 0.17.2 but the cloud integration is on 0.17.0. I have the latest versions installed

**Comment by dotvezz** [comment]
@fmonday interesting! A few questions:

1: What's your region?
2: Does the old workaround (log out/in on the mobile app) work for you?

**Comment by fmonday** [comment]
I'm in the US; no, the workaround didn't work. 
However, I found my device credential (which I had stored from use of `get_devices.py` a long time ago) and managed to reconnect manually.
