### ISSUE TITLE
Empty popup when setting up the integration

### ISSUE THREAD

**Issue by revolter** [libdyson-wg/ha-dyson#60]
<img width="407" alt="image" src="https://github.com/libdyson-wg/ha-dyson/assets/5748627/71446191-8bd9-4089-94de-8ce39eb2aae4">

Are you aware of this issue? Is there a way that I can investigate / debug this for you?

**Comment by dotvezz** [comment]
Wow, that's a new one. Hopefully we can get it sorted out for you. Could you provide the following information?

1. Which step of the setup were you on?
   - If it wasn't the first step, what options did you pick to get here?
2. Can you enable debug logging, try again, and tell if anything shows up in the logs?
3. Home Assistant version?
4. Which Dyson devices do you have?
   - This is likely not relevant to your specific bug, but asking just in case.

**Comment by tom-1804** [comment]
same here. after language selection only empty popups, but with fields. after restarting the browser the problem is solved.
here the fields in the right order:
- Language
- Mail
- Password & myDyson verification code (check your mails)
thats it.
you can fill it blind or try to restart the browser or take another browser.

**Comment by dotvezz** [comment]
Oh, I wonder if this is translation-related? The only language used right now in this Integration's translation files is English. I can add Korean and machine-translate from Korean to probably-good-enough Japanese, but I'd personally struggle for any other language.

**Comment by revolter** [comment]
@dotvezz,

1. `Settings` > `Devices & Services` > Add integration` > `Dyson` > `Setup automatically with your MyDyson Account` > `Romania (RO)` > "my email address"
2. How do I do that?
3.

```
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest
```
4. `Dyson Pure Hot+Cool`

---

When adding an integration, if I choose `Dyson Cloud` instead, the flow is like this: `Romania (RO)` > "my email address" > "my password" & "MyDyson verification code", but I get stopped here because I forgot my password and I can't reset it. But that repo says that "This integration's features have all been merged into https://github.com/libdyson-wg/ha-dyson/ and is not needed or maintained anymore.", so I expected for this repository to behave the same.

**Comment by revolter** [comment]
Hmm, while playing with all these HACS repositories and whatnot, I remember that, at some point, I saw some fields with no placeholders, and didn't know what to input in them 🤔 But I don't think that it's translation related, because I'm using English.

**Comment by dotvezz** [comment]
@revolter it's been a while. I was never able to reproduce your issue, so I'm wondering if it still happens for you.

**Comment by revolter** [comment]
Yes, but I found out later that it's not specific to this integration, so I will close it in favor of https://github.com/home-assistant/frontend/issues/17526.
