### ISSUE TITLE
Connection issues 

### ISSUE THREAD

**Issue by TheRecovery007** [libdyson-wg/ha-dyson#61]
Hi,

It seems like i have connection issues to my dyson fan after the homeassistant os update.

Fan kept beeing offline so i tried to reinstall and configure the integration.
Connecting to the account has no issues but configuring the discovered fan results in:

"Failed to connect. The IP Address may be required if your Home Assistant installation is running in a Container or a VM."
Even while filling in the ip

**Comment by bdovaz** [comment]
Same problem

**Comment by dotvezz** [comment]
Hi @bdovaz and @TheRecovery007 - thanks for dropping in. Sorry to hear this isn't working for you. If you'd be able to answer a few questions for me, hopefully I can help solve the issue for you.

1. Do the Dyson devices respond to ping?
2. How are you running your Home Assistant installation? (Container? VM? Home Assistant OS? etc etc)
3. Which Dyson devices do you have?

There are also some debugging tools available if you'd like to try them:


1. Run [get_devices.py](https://github.com/libdyson-wg/libdyson-neon/blob/main/get_devices.py) to get device information.
    - You'll need to clone that repo, install Python, the `pip` package manager, and run `pip install requirements.txt` to download required dependencies for the script.
 2. Save the following information from that script:
     - **Device Type** (I'll need to add this to [const.py](https://github.com/libdyson-wg/libdyson-neon/blob/main/libdyson/const.py).)
     - **Serial** and **Credential** (I don't need these, don't share them. You'll need them for the next step though)
 3. Run [dyson-mqtt-listen](https://github.com/dotvezz/dyson-mqtt-listen) to get mqtt messages from the device. This is how we'll double-check that all the status/sensor messages are using the same format as previous devices.
    - You can download the executable binary for your platform of choice on [the release page](https://github.com/dotvezz/dyson-mqtt-listen/releases/tag/v1.0.0).
    - When running it, you'll need to use the flags for [devices without wifi stickers](https://github.com/dotvezz/dyson-mqtt-listen#devices-without-wifi-stickers).
    - Feel free to copy-paste the output here with your serial number redacted for privacy. I only need the json message bodies.
    
I understand this is a **_lot_**, let me know if you have any questions on performing any of these steps. Hopefully we'll get you squared away!

**Comment by bdovaz** [comment]
In my case it has been fixed, it must have been an intermittent error.

**Comment by TheRecovery007** [comment]
For me it seems to be fixed as well. yesterday it did not work but today it worked without any issue

**Comment by dotvezz** [comment]
Interesting! Glad it's working, I'll cross my fingers and hope it stays that way. Closing this issue, but please feel free to follow up if you have any more issues and we can reopen it.
