### ISSUE TITLE
HP09 Failing to connect w/ IP Address

### ISSUE THREAD

**Issue by TonyMontuna** [libdyson-wg/ha-dyson#67]
Setup: 

-Dell Optiplex 7050 i5 12gb ram 128gb ssd
-HA OS 2023.9.1

Issue: 

-The fan went offline September 1 at 9PM 
-This tells me it wasn't an update of HA and likely isn't due to the new release 

Troubleshooting Steps Taken: 

1. Restart HA (Power) 
2. Reload Config
3. Delete Device 
4. Re-Authorize Dyson Login to setup new device through config
5. HA finds Device 
6.Initial Submit did not enter IP 
7. Error "Failed to connect. The IP Address may be required if your Home Assistant installation is 8. running in a Container or a VM."
9. I enter IP address (confirmed from AngryIP) of HP09
10. Same error as Above 
11. Repeat

**Comment by dotvezz** [comment]
Hey @TonyMontuna 

I wonder if you're able to run the troubleshooting tool as described in this comment here: https://github.com/libdyson-wg/ha-dyson/issues/23#issuecomment-1660271507

**Comment by dotvezz** [comment]
@TonyMontuna it's been a minute and I just wanted to check in here - did you have a chance to go over my previous comment?

**Comment by dotvezz** [comment]
Closing this issue for now as it's been inactive for so long - please feel free to follow up if you're able to though, happy to reopen it to get your issue solved!
