### ISSUE TITLE
Dyson Pure Hot+Cool no entity for oscillation?

### ISSUE THREAD

**Issue by maxedmini** [libdyson-wg/ha-dyson#74]
hi just moved over from the old integration and all added fine but I no longer have a seperate entity for oscillation so when adding into HomeKit a with is no longer populated ?
any workarounds for this 
thanks

**Comment by maxedmini** [comment]
scrap that I found it in HomeKit now it look like in now created 2 separate devises 1 for heating and 1 for fan

**Comment by maxedmini** [comment]
ok so it is in HomeKit but it does no populate as a standalone switch like it use to so its very hard to use/find
anyway to put this back to how it use to be?

**Comment by dotvezz** [comment]
Hmm, ineresting. I don't know anything about the Homekit side of things, so I might ask you to be patient with me on that area.

For this integration, there shouldn't be any difference in fan oscillation settings compared to Shen's old integration. However, in the past few months Home Assistant has overhauled their Fan entity which provides the Oscillation control. Is it possible you also updated Home Assistant around the same time you migrated to this integration?

**Comment by dotvezz** [comment]
It's been a while since the last message. I'll mark it as closed, but feel free to reopen if you need to!
