### ISSUE TITLE
Change Request in the Read.me or the setup screen - cloud 

### ISSUE THREAD

**Issue by fabiankrauss** [libdyson-wg/ha-dyson#75]
Hey firstly:

big thanks for your work!

I set up my integration with the cloud log in - finally.
But I had a hard time to understand what's the 2nd line under the password.

A short remark to the OTP-Code sent by mail would help :)

BR
Fabian

**Comment by dotvezz** [comment]
Hi @fabiankrauss! Glad you eventually figured it out, but sorry you had a hard time. I can definitely update the readme to help people in the future.

The field is supposed to have a label with advice to "check your email" - was that visible in your case?

**Comment by dotvezz** [comment]
Updated the readme. But I'm still curious if the field showed the "Check your email" label - feel free to follow up here even though I've closed the issue.
