### ISSUE TITLE
Current Humidity: off

### ISSUE THREAD

**Issue by kramttocs** [libdyson-wg/ha-dyson#84]
I have a Pure Hot+Cool and a Pure Hot+Cool Link.
The HC shows the humidity in the thermostat view correctly: 

![image](https://github.com/libdyson-wg/ha-dyson/assets/11565750/139a806f-d833-4e9d-b5ad-410b1047c71a)

The HCLink does not:

![image](https://github.com/libdyson-wg/ha-dyson/assets/11565750/b3bed4a4-9d1a-4e9c-8032-595cbe5aecea)

Both fans show the Humidity correctly in the sensor. It's just the thermostat view.

**Comment by kramttocs** [comment]
Disregard. I had reloaded the integration twice but on the third time it worked (right after posting this).

**Comment by dotvezz** [comment]
>  it worked (right after posting this).

@kramttocs I know that feeling too well! Glad it's working, but feel free to drop back and reopen if you see the issue again.
