### ISSUE TITLE
List of Expected Sensors in HA from certain devices (e.g. TP02)?

### ISSUE THREAD

**Issue by ziptbm** [libdyson-wg/ha-dyson#89]
This isn't really an issue, but rather a question.  I have two Dyson TP02s that I just configured via this integration after realized that the previous one I was using hasn't been updated for some time (shenxn/ha-dyson).  What sensors should I see in HA and what units should they be using?

The previous one showed the following:

1. Temperature in degrees
2. Humidity in percent
3. Particulates in ug/m3
4. VOC in ug/m3

With this integration, it also shows 4 sensors, but Particulates and VOC have been replaced by Air Quality Index and VOC Index, with no units.  Is this an index from 0-10?  

I like the index approach, but also liked the raw data.  Is that not possible with this integration?  Thanks for the clarification!

**Comment by dotvezz** [comment]
@ziptbm sorry for the slow reply here! 

There are a few (now closed) threads have conversation for context, I'm happy to dig them up if you like. The short version is this: Unfortunately, the index _is_ the raw data coming from the device. Shen's work is awesome and I'm standing on his shoulders, but that was one unfortunate problem: Whoever made that contribution assumed that 0555 meant "555 ug/m3" when it actually meant "Index value of 5.55.

So the sensors were replaced with Index sensors to be more correct.

I'll close this issue, but feel free to follow up of course!

**Comment by ziptbm** [comment]
@dotvezz thanks for the context.  Then I'll assume the ones I have are correct and use the index moving forward.   I just got the TP02 and was wondering if the TP04 or TP07 have other sensors, that was the reason for my question.   Thanks again!
