### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Silther** [libdyson-wg/ha-dyson#90]
The dyson app allows you to set a timer to switch off the fan after the specified time, could that be implemented?

**Comment by dotvezz** [comment]
Hmmm, maybe! I've been a bit bogged down with life, but investigating a good way to do this sounds fun. Will follow up when I have more info.

**Comment by bdovaz** [comment]
But isn't it already done @dotvezz? Or have I misunderstood?

https://github.com/libdyson-wg/ha-dyson/blob/ee89dc961ab062dbf0cc24a2fa3b5c1895750aec/custom_components/dyson_local/services.yaml#L18

**Comment by codyc1515** [comment]
Looks like the relevant methods are:

- _device.sleep_timer to get numeric value
- _device.set_sleep_timer to set timer & input numeric value between 1 & 540 inclusive
- _device.disable_sleep_timer to disable timer

I will take a look at this now.
