### ISSUE TITLE
Failed to setup, no devices or entities

### ISSUE THREAD

**Issue by lolongan** [libdyson-wg/ha-dyson#91]
Hello,

I have one Pure Hot+Cool and one Purifier Hot+Cool Formaldehyde.
First I tried to setup using MyDyson account. The account is setup but no device is found.
Here is the error log:

> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/__init__.py", line 108, in async_setup_entry
>     return await async_setup_account(hass, entry)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/__init__.py", line 79, in async_setup_account
>     devices = await hass.async_add_executor_job(account.devices)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/vendor/libdyson/cloud/account.py", line 210, in devices
>     devices.append(DysonDeviceInfo.from_raw(raw))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/vendor/libdyson/cloud/device_info.py", line 31, in from_raw
>     decrypt_password(raw["LocalCredentials"]),
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/vendor/libdyson/cloud/utils.py", line 31, in decrypt_password
>     json_password = json.loads(_unpad(decrypted))
>                                ^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/vendor/libdyson/cloud/utils.py", line 19, in _unpad
>     return string[: -ord(string[len(string) - 1 :])]
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: ord() expected a character, but string of length 0 found

Then I tried to setup using manual entry.
I succeeded to add the Pure Hot+Cool but failed to add the Purifier Hot+Cool Formaldehyde.
Reading other issues, I understand that it is not possible to add the Purifier Hot+Cool Formaldehyde using manual entry.
Please note that the Purifier Hot+Cool Formaldehyde does appears in MyDyson app and I can ping its IP address from within HA.
Do you have any fix ?

Thanks in advance.
Lolongan

**Comment by dotvezz** [comment]
@lolongan thanks for posting here! Looking at the logs, it looks like the Dyson API may have returned an empty or invalid response. Sorry to be a bother, but could you try again and see if it works now? If not, let me know and I'll be happy to help troubleshoot.

**Comment by lolongan** [comment]
@dotvezz Thanks for your reply. I have just retried again but the issue remains. Exact same error log as above.
I wonder if it is because I have also other devices (lamp, hair dyer) registered in my Dyson account.
So, I create a brand new My Dyson account, register only my 2 Hot+Cool devices and set up  the integration again with this new account. This time, there is no more error but the integration entries still say that there is no devices or entities attached to this account. So back to square 1 :(

**Comment by dotvezz** [comment]
@lolongan interesting.... Seems like your issue is resolved at least, so I'll mark this closed. Feel free to reopen if you need to though.

On the Dyson Account side, I'll keep an eye out for other similar issues like this. If it gets to be too common and we can identify some pattern, I should add that to the readme's troubleshooting section. Thanks for the info, really appreciate it!
