### ISSUE TITLE
climate-entity for Dyson TP09 missing

### ISSUE THREAD

**Issue by Thomas-W72** [libdyson-wg/ha-dyson#96]
Hello,

how can I add the climate-entity for Dyson TP09 Purifier Cool? I also added the Dyson HP09 Purifier Hot+Cool and there I do have the climate-entity and for the HP09 I can use the thermostat-card. I want to add a thermostat-card also for the TP09.

I am using the integration version v1.3.3 and already tried to delete and add the TP09 again.

Thanks and regards,
Thomas

**Comment by dotvezz** [comment]
Hi @Thomas-W72!

This is because of the limitations of the devices themselves. Unlike the HP series which has a configurable heater thermostat, here's no climate entity for the TP series because they don't have any kind of temperature-setting feature.

But I'm curious what your usecase is; maybe there's a creative way to support your needs. Please let me know what your thoughts are!

**Comment by Thomas-W72** [comment]
Hi @dotvezz ,
thanks for your response. You're right, it's not possible to adjust the temperature. I would like to adjust the speed of the fan by the  "circle", would like to see the actual temperature and humidity and would like to switch the device on/off and also activate/deactivate the automatic-mode direct from the card. If it would be possible to see the HCHO indication (maybe just the color) and also an icon for activate/deactivate the rotation, that would be great.

**Comment by Thomas-W72** [comment]
Hi @dotvezz , thanks for reminder. I tried to integrate your suggestion, but I didn't get it. I am just a newbie to HA ;-) Which card do I have to use for the Fan speed slider?
Actually I got the following, but without fanspeed.. only in details I see the power, oscillation, mode...
![image](https://github.com/libdyson-wg/ha-dyson/assets/5254505/661937b1-580a-4c9d-be54-2e8dcc0c3dd5)

**Comment by dotvezz** [comment]
@Thomas-W72 Ahhh, I'd recommend using this [Purifier card](https://github.com/denysdovhan/purifier-card) that's available from HACS.

While Home Assistant provides a fan _entity_, it strangely doesn't provide a suitable card by default.

**Comment by dotvezz** [comment]
I'll close this issue, but please feel free to reply if you have any more questions!
