### ISSUE TITLE
Device found but 'Unknown Error Occurred' when I try to configure device

### ISSUE THREAD

**Issue by joeygray0519** [libdyson-wg/ha-dyson#97]
It happens whether I enter the ip address or not.

**Comment by dotvezz** [comment]
Hi @joeygray0519! Can you provide more information?

1. What devices is it?
2. What configuration method are you using?
3. What version of this integration are you using?
4. What version of Home Assistant are you running?
5. How are you running Home Assistant (Container? venv install? Something else?)
6. Can you enable debug logging and post logs here?

**Comment by joeygray0519** [comment]
Hi! Thanks for replying. Apologies for the lack of info-- was having a rough day. 


I was using My Dyson account but I tried again with the SSID/Password sticker and it worked fine.

**Comment by dotvezz** [comment]
> Apologies for the lack of info-- was having a rough day.

I know that feeling lol, no worries.

> I tried again with the SSID/Password sticker and it worked fine.

Sounds like maybe there was some intermittent issue? The SSID/Password follow the same connection path as the My Dyson account. For now I'll close the issue, but definitely feel free to reopen if you have continued problems!
